version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: ai_learning
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dmalky100@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    build: .
    container_name: ai_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password1234@db:5432/ai_learning
      PYTHONPATH: /backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend

volumes:
  db_data:
  pgadmin_data:
